[project]
name = "investingbriefingbot"
version = "0.1.0"
description = "investing helper"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.86.0",
    "pybit>=5.14.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "tinydb>=4.9.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.6",
]
